### ISSUE TITLE
Dynamic Lights List + Optifine

### ISSUE THREAD

**Issue by naqaden** [Shinoow/DarknessLib#3]
I use DarknessLib for Grue, but figured I'd add dynamic light to some items for fun.

Relevant configs:
```
ofDynamicLights:2
```
```
S:"Dynamic Lights List" <
    minecraft:golden_carrot
>

B:"Dynamic Lights Mode"=true
```

After a restart, holding golden carrots now prevents Grues from spawning, but they don't cast dynamic light like handheld torches or glowstone dust. For now as a workaround I'm using **dynamic_lights.properties**.

Minecraft Forge 14.23.5.2855
OptiFine 1.12.2 HD U G5
DarknessLib 1.12.2-1.1.2

**Comment by Shinoow** [comment]
Maybe I should emphasize it a bit more on the mod page, but DarknessLib only tells other mods server-side that "this player is currently emitting [INSERT LIGHT LEVEL] with the item they're holding", while on the client side you have to configure the mod providing dynamic lights to make the item emit light (assuming it can be configured to do so, otherwise... meh).

**Comment by naqaden** [comment]
I see! Yes, I misunderstood the meaning of "Dynamic Lights List" to visually cast dynamic light from custom items.

I'll close this since it's working as intended. Thanks for clarifying.
